Several improvements and additions for deploying DB2 (#496)
* Bugfix nproc unlimited for dbsidadm group, not db2sidadm group

* Use virtual_host from hostvars (inventory) for DB2 installation

* Fixed DB2 log_dir mountpoint

DB2 log_dir was mounted on /log/SID/dir instead of /db2/SID/log_dir

* Fix Agent_IP variable for sap_library

* Remove become and orchestration user for delegated VmAgentActions tasks

* Improve 2.10-sap-notes tasks

* Optimize SAP OS USERS and Group Creation (user_nw) tasks

* Remove unused input-api variables

* Add custom virtual_hostname variabels for db, ers, scs and pas

* Add vars for ASCS/ERS NFS filesystem devices when not using AFS or ANF

* Bugfix data source azuread_service_principal

Error: Unsupported argument on imports.tf line 49, in data "azuread_service_principal" "sp": client_id = local.spn.client_id
An argument named "client_id" is not expected here.

one of `application_id,display_name,object_id` must be specified

* Contain setting of HANA schema name to only execute when deploying HANA