Final PR for release v3.9.3.0 (#500)
* Merge from main to experimental (#490)

* remove duplicate definitions

* remove duplicate

---------

Co-authored-by: Kimmo Forss <kimforss@microsoft.com>

* Prepare for hotfix 3.9.2.0

* Add permissions for control plane SPN

* Updated variable name

* Change provider for network links

* Undo

* Change provider

* Update the ref in the resources.yml

(cherry picked from commit 082613a80dc1aa636c33dfdc7e235c03abe4c7f1)

* changes required for release 3.9.2.0

* skip resource provider

* HotFix 3.9.3

* Preparation for hotfix release 3.9.3

* Add the missing exports

* Update advanced state management

* move second parameter

* Add verbosity

* Update pipeline

* remove the vault

* remove the quotes

* add the getopt values

* move the order

* Don't create the configuration variables

* Switch the if statement

* Don't reset the step

* Add the support for test only for workload zone as well

* Name rationalization

* Add support for multiple IP ranges

* Using a list

* adress space check

* change the address space to list

* use the correct output

* Use the renamed output storageaccount_resourcegroup_name

* Don't perform deployment if not logged on as SPN

* format

* simplify network logic

* Fix the logic for deployer configuration

* Fix deployer and flatten the list of vnets

* Fix the list of vnets

* remove the set statements

* Version update and fault domain counter

* Update the template

* Web App updates

* Variable renames

* Update pipeline

* Package updates

* Add support for multiple address ranges

* Change HTML IDs

* deployment task

* Update Azure Identity

* More informative task names

* Feng shui

* change the dns creation logic

* Fixes for IPs

* Default upgrade packages to false

* Switch to use instance metadata

* Add support for extending packages, mounts etc

* Rel 9.2 support

* Add support for dynamically retrieval of SWPM10

* hdbuserstore updates

* pacemaker updates

* Load Balancer timeout updates

* Format the Terraform files, add support for tags for all resources

* Start documentation of variables

* Add support for providing tags for all resources

* Support deployerless deployments

* Add missing tags

* Web App updates (tag support)

* Add a dependency on the private end point

* Add dependency for container

* Work on the dependency map

* Add a dependency on the storage account network rules

* Make the public access same for both storage accounts

* change the dependency order

* store the state file if failure when removing

* Adding the missing parameters

* Set permissions on variable groups

* Fix the Invoke-Restmethod call

* Allow resetting of PAT

* Fix typo

* Resetting of PAT

* allow reusing of repo

* Add permissions to pipelines

* Simplify the query

* Add a pause

* Remove default access for all pipelines

* Don't show Invoke-RestMethod response

* Add pipelines permissions for pool

* Don't set permissions on pools (yet)

* Add permissions on agent pools

* Use the queue id and not the pool ID

* Add more info

* Final version for next release

* prepare for release 3.9.3.0

* install lint 6.20.3 for the workflow as we are not ready to 6.21 yet.

* suppress tracing when checking variables

* Lint fixes

* Linting

* remove extended character

* Pull in main

* Several improvements and additions for deploying DB2 (#496)

* Bugfix nproc unlimited for dbsidadm group, not db2sidadm group

* Use virtual_host from hostvars (inventory) for DB2 installation

* Fixed DB2 log_dir mountpoint

DB2 log_dir was mounted on /log/SID/dir instead of /db2/SID/log_dir

* Fix Agent_IP variable for sap_library

* Remove become and orchestration user for delegated VmAgentActions tasks

* Improve 2.10-sap-notes tasks

* Optimize SAP OS USERS and Group Creation (user_nw) tasks

* Remove unused input-api variables

* Add custom virtual_hostname variabels for db, ers, scs and pas

* Add vars for ASCS/ERS NFS filesystem devices when not using AFS or ANF

* Bugfix data source azuread_service_principal

Error: Unsupported argument on imports.tf line 49, in data "azuread_service_principal" "sp": client_id = local.spn.client_id
An argument named "client_id" is not expected here.

one of `application_id,display_name,object_id` must be specified

* Contain setting of HANA schema name to only execute when deploying HANA

* alingment on task and set execution bit for the acss-registration shell script.

---------

Co-authored-by: Kimmo Forss <kimforss@microsoft.com>
Co-authored-by: Harm Jan Stam <harmjan+git@harmjan.com>